version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: assessment-may-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB?Variable not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable not set}
      TZ: "Asia/Jakarta"
    ports:
      - ${POSTGRES_DB_EXPOSE_PORT?Variable not set}:${POSTGRES_DB_PORT?Variable not set}
    networks:
      - svc-network
    volumes:
      - postgre_data:/var/lib/postgresql/data
      - ./data/postgres:/docker-entrypoint-initdb.d
  account:
    build:
      context: ./services/account
      dockerfile: Dockerfile
    container_name: svc-account
    depends_on:
      - redis
      - db
    ports:
      -  ${ACCOUNT_SVC_PORT?Variable not set}:${ACCOUNT_SVC_PORT?Variable not set}
    networks:
      - svc-network
    volumes:
      - ./services/account:/app
  mutasi:
    build:
      context: ./services/mutasi
      dockerfile: Dockerfile
    container_name: svc-mutasi
    depends_on:
      - redis
      - db
    ports:
      -  ${MUTASI_SVC_PORT?Variable not set}:${MUTASI_SVC_PORT?Variable not set}
    networks:
      - svc-network
    volumes:
      - ./services/mutasi:/app
  redis:
    image: "redis:alpine"
    container_name: redis-assessment
    ports:
      - "${REDIS_PORT?Variable not set}:${REDIS_PORT?Variable not set}"
    networks:
      - svc-network
  

volumes:
  postgre_data:

networks:
  svc-network:
  